#Pearl starts 2/16
opra = 0
stockprice = 2
ase = 4
bat = 5
bse = 6
cc2	= 7
cbo = 8
ise = 9
ndq = 10
nys = 11
phs = 12
mia = 13
tbo = 14
gem = 15
edx = 16
mer = 17
mpl = 18
order = 20
ase2 = 22
bat3 = 23
bse2 = 24
cc22 = 25
cbo2 = 26
ise2 = 27
ndq2 = 28
nys2 = 29
phs2 = 30
mia2 = 31
tbo2 = 32
gem2 = 33
edx2 = 34
mer2 = 35
mpl2 = 36
underlying = 0
bidSize = 1
bidPrice = 2
askSize = 3
askPrice = 4

	#aseInfo = quoteList[ase].replace('/', ' ').split(" ")
	#batInfo = quoteList[ase].replace('/', ' ').split(" ")
	#cc2Info = quoteList[ase].replace('/', ' ').split(" ")
	#cboInfo = quoteList[ase].replace('/', ' ').split(" ")
	#iseInfo = quoteList[ase].replace('/', ' ').split(" ")
	#ndqInfo = quoteList[ase].replace('/', ' ').split(" ")
	#nysInfo = quoteList[ase].replace('/', ' ').split(" ")
	#phsInfo = quoteList[ase].replace('/', ' ').split(" ")
	#miaInfo = quoteList[ase].replace('/', ' ').split(" ")
	#tboInfo = quoteList[ase].replace('/', ' ').split(" ")
	#gemInfo = quoteList[ase].replace('/', ' ').split(" ")
	#edxInfo = quoteList[ase].replace('/', ' ').split(" ")
	#merInfo = quoteList[ase].replace('/', ' ').split(" ")
	#aseInfo = quoteList[ase].replace('/', ' ').split(" ")
	#aseInfo = quoteList[ase].replace('/', ' ').split(" ")